return {
	ensure_installed = {
		"lua-language-server",
		"bash-language-server",
		"black",
		"css-lsp",
		"html-lsp",
		"isort",
		"lua-language-server",
		"prettierd",
		"pyright",
		"shfmt",
		"stylua",
		"yaml-language-server",
		"prettier",
		"harper-ls",
		"shellcheck",
	},
	automatic_installation = true,
}
